import turtle as t
from Rectangle import Rectangle

def BackgroundOfFlag(x, y):
    Back = Rectangle(_xCor=x, _yCor=y, _fillColor='white')
    Back.setFillColor('red')
    Back.moveTurtle()
    Back.drawWithColor()
    Back.updateXCor(100)
    Back.moveTurtle()
    Back.setFillColor('White')
    Back.set_height(150)
    Back.set_Length(100)
    Back.drawWithColor()
    Back.setYCor(-75)
    Back.moveTurtle()

def drawRightHalfLeaf():
    t.penup()
    t.setposition(0,100)
    t.pendown()
    t.right(60)
    t.forward(50)
    t.left(95)
    t.forward(35)
    t.right(135)
    t.forward(75)
    t.left(140)
    t.forward(50)
    t.right(110)
    t.forward(25)
    t.left(80)
    t.forward(50)
    t.right(140)
    t.forward(50)
    t.left(100)
    t.forward(25)
    t.right(110)
    t.forward(75)
    t.left(90)
    t.forward(20)
    t.right(140)
    t.forward(75)
    t.left(100)
    t.forward(75)
    t.right(90)
    t.forward(10) 
def drawLeftHalfLeaf():
    t.penup()
    t.setposition(0,100)
    t.pendown()
    t.left(60)
    t.forward(50)
    t.right(95)
    t.forward(35)
    t.left(135)
    t.forward(75)
    t.right(140)
    t.forward(50)
    t.left(110)
    t.forward(25)
    t.right(80)
    t.forward(50)
    t.left(140)
    t.forward(50)
    t.right(100)
    t.forward(25)
    t.left(110)
    t.forward(75)
    t.right(90)
    t.forward(20)
    t.left(140)
    t.forward(75)
    t.right(100)
    t.forward(75)
    t.left(90)
    t.forward(10)

def drawRedLeaf():
    t.color("red")
    t.begin_fill()

    # Draw the leaf outline
    for _ in range(2):
        t.forward(100)
        t.right(45)
        t.forward(100)
        t.right(135)

    t.end_fill()


if __name__ == "__main__":
    t.speed('slow')
    # BackgroundOfFlag(-300, 0)
    drawRightHalfLeaf()
    drawLeftHalfLeaf()
    # drawRedLeaf()
    t.mainloop()


